### ISSUE TITLE
abortEarly

### ISSUE THREAD

**Issue by douglasscriptore** [wgrisa/express-yup-middleware#1]
I'm not able to pass the {abortEarly: false} property, to list all errors at once

**Comment by wgrisa** [comment]
> I'm not able to pass the {abortEarly: false} property, to list all errors at once

Hi @douglasscriptore, please try to use it as presented below:

```ts
{
  schema: {
    body: {
      yupSchema: ...,
      validateOptions: { abortEarly: false },
    },
  },
  errorMessages,
}
```

If it doesn't work for you, please share your code. Thanks ;)

**Comment by wgrisa** [comment]
I'll assume my suggestion fixed your issue @douglasscriptore. Please feel free to comment and reopen otherwise.
