### ISSUE TITLE
Unnecessary production dependencies

### ISSUE THREAD

**Issue by yaneek** [wgrisa/express-yup-middleware#17]
I have found this dependencies in your project, most of them are unnecessary:
```
  "dependencies": {
    "@types/express": "^4.17.3",
    "@types/yup": "^0.26.33",
    "express": "^4.17.1",
    "http-status-codes": "^1.4.0",
    "ts-node": "^8.8.1",
    "typescript": "^3.8.3",
    "yup": "^0.28.3"
  },
```

`typescript` + `@types/*` + `ts-node` - should be located in "devDepencdencies"
`express` + `yup` - are required only for "typescript types". Maybe this dependencies should be located in "peerDependecies"? or "devDependencies" also?

**Comment by wgrisa** [comment]
Thanks for sharing! I've moved most of these. Will double check how to proceed with express and yup. Feel free to open a PR ;)
