### ISSUE TITLE
Question/Bug: Response should include all the error messages but it only returns one

### ISSUE THREAD

**Issue by ovidb** [wgrisa/express-yup-middleware#6]
First, your library is very useful so thanks for putting it out there. I was thinking of writing one myself, but since I found yours I'm planning to use it.

One thing I found out while evaluating the library, and not sure if it's a bug or missing feature.

Essentially the validation seems to only be returning the first error. It looks like the response is of type Array so I'm thinking that the plan was to return all the errors?

For example with the following Yup schema:
```
export const SignUpSchema = Yup.object().shape({
  email: Yup.string()
    .email('Invalid email address')
    .required('An email address is required'),
  firstName: Yup.string().required(
    'In order for us to get acquainted we need to know your first name'
  ),
  lastName: Yup.string().required(
    'In order for us to get acquainted we need to know your last name'
  ),
});
```

When I perform a request with an empty body, the response is:
```
{
    "errors": {
        "body": [
            {
                "message": "In order for us to get acquainted we need to know your last name",
                "propertyPath": "lastName"
            }
        ]
    }
}
```

And I believe the desired outcome should be:

```
{
    "errors": {
        "body": [
            {
                "message": "An email address is required",
                "propertyPath": "email"
            },
            {
                "message": "In order for us to get acquainted we need to know your last name",
                "propertyPath": "firstName"
            },
            {
                "message": "In order for us to get acquainted we need to know your last name",
                "propertyPath": "lastName"
            },
        ]
    }
}
```

**Comment by wgrisa** [comment]
Hi @ovidb! Many thanks for your feedback and for using the library :)

We've added a new test and improved our readme covering this case.

https://www.npmjs.com/package/express-yup-middleware#using-yup-validation-options

Please take a look and let us know if it solves your problem.

**Comment by ovidb** [comment]
@wgrisa 
> Please take a look and let us know if it solves your problem.

It does indeed. 👍 👏 I'll close this.
Thanks a lot.
